### ISSUE TITLE
Password Generator

### ISSUE THREAD

**Issue by hebz26** [hebz26/mypass-manager#1]
From the project doc: 
"
Suggest strong password (password generator). Apply the **Builder pattern** to create complex passwords with specific requirements (length, complexity). Weak master password warning. Apply the **Observer pattern** to notify users in the events of weak password, 
"
Navigate to src/components/authform/signup.jsx . in signup.jsx, adjust the code to have a button that suggests a strong password and inputs it in the password field. the user should still have the option to choose their own though. user should be able to click this multple times and each time a new password is suggested in the field. also implement a weak master password warning if the user inputs their own weak one. Try to make seperate components for this so the code isnt bulky and make sure you apply the builder pattern for generating the password and observer pattern for the weak warning. comment your code where you are applying the design pattern.

**Comment by afrah30** [comment]
Should be all ready to go. Let me know if any other issues arise. Added UML Diagrams on sheets.
